### ISSUE TITLE
Get slice timings

### ISSUE THREAD

**Issue by egarza** [BIDS-Apps/CPAC#12]
Perhaps it`s a silly question but, reading the manual it says BIDS needs the precise slice acquisition times to perform slice timing correction. What tool can I use to get the times? Dcm2Bids doesn't do it nor I can get it from the nifti header so I guess it should be on the DICOM header? Or how do you guys do it?

Thanks

Ed

**Comment by chrisgorgo** [comment]
dcm2niix and heudiconv are able to extract that information from DICOMs.
It's always good to validate it with the sequence specification.

**Comment by egarza** [comment]
Thanks, I'll try that. Also, I've been told to convert from Dicom to Nifti using AFNI for the same info.
