### ISSUE TITLE
CPAC runs, but no Reports

### ISSUE THREAD

**Issue by egarza** [BIDS-Apps/CPAC#13]
It is normal not to get the HTML reports in the logs folder? I ran a participant and it finished without errors, with everything I needed in the output, but the report doesn't show anything.

Thanks

Ed

**Comment by ccraddock** [comment]
Was report generation turned on in the configuration ?

**Comment by egarza** [comment]
Good question, no idea because I don't have the GUI control and didn't know you had to activate it. Here are my YML in TXT.

[cpac_data_config_20170808192708.txt](https://github.com/BIDS-Apps/CPAC/files/1212200/cpac_data_config_20170808192708.txt)

[cpac_pipeline_config_20170808192708.txt](https://github.com/BIDS-Apps/CPAC/files/1212201/cpac_pipeline_config_20170808192708.txt)

**Comment by egarza** [comment]
Can't find a "report" option there.

**Comment by mnarayan** [comment]
I have the same issue. @ccraddock I do have the reports option turned on in the configuration file (I don't use the GUI) but the html reports are still empty.

**Comment by ccraddock** [comment]
The report feature has been temporarily removed due to several bugs. We are currently working on a fix and will reactivate when it is finished. Not sure when this will be yet, but will try to update you when we figure it out.

**Comment by ccraddock** [comment]
This should be back in v1.2 which will be released very soon.
