### ISSUE TITLE
cpac_templates.tar.gz unzips in wrong directory

### ISSUE THREAD

**Issue by jdkent** [BIDS-Apps/CPAC#28]
The [default_pipeline.yaml](https://github.com/BIDS-Apps/CPAC/blob/master/default_pipeline.yaml#L333) assumes cpac_templates is within cpac_resources, currently it's unpacking in the root directory.
#27 fixes this

**Comment by ccraddock** [comment]
i beleive that this has been fixed with the newer version of the container
