### ISSUE TITLE
Reference a particular version of C-PAC

### ISSUE THREAD

**Issue by chrisgorgo** [BIDS-Apps/CPAC#4]
Currently the App is using the latest version of C-PAC from a particular branch: 

https://github.com/BIDS-Apps/C-PAC/blob/master/cpac_install.sh#L872

For the Docker cache to work properly a the installation script needs to point to a particular commit or tag. This way when you update the commit hash in the install script you will trigger rebuilding of the image.

**Comment by ccraddock** [comment]
waiting for cpac v0.4.0 merge to happen this afternoon, after which i will apply the tag.

**Comment by ccraddock** [comment]
took me a minute to understand what you were suggesting, but now I get it. The tag is explicitly set in the installation file so that it must be manually updated for each new release. Which will also trigger building a new Docker image for dockerhub.
