### ISSUE TITLE
Tests time out

### ISSUE THREAD

**Issue by chrisgorgo** [BIDS-Apps/CPAC#7]
CircleCI has a limit of running no longer than 2h. This seems to be too short to perform full analysis of one subject. Would it be possible to limit the analysis for the testing purposes only to a couple of first testing steps? This is what I did for FreeSurfer and HCPPipelines apps.

**Comment by ccraddock** [comment]
Hmm. I will try with a pipeline configure with Paramus that should make somethings faster.

**Comment by ccraddock** [comment]
i stripped down the config to perform anatomical and anatomical preprocessing only, no statistical derivatives (such as reho, alff, etc). this pipeline is in test_pipeline.yaml and takes about 45 min to run 1 anatomical and 2 functional scans.
