### ISSUE TITLE
Installing AFNI using CPAC install script

### ISSUE THREAD

**Issue by raamana** [BIDS-Apps/CPAC#8]
Hi Cameron,

I am trying to use the CPAC install script to install FSL and AFNI to build my docker. It worked fine during the sprint, and I notice the download locations for the installer script has been changed from nih.gov to amazonws and which seems to fail also.

Did you guys try to build the Dockerfile in this repo recently? Does it work for you now?  As the URLs and host servers locations are changing, is there a way to make it static or you have other suggestions to make this easier and less reliant on an internet download? Thanks.

cc @chrisfilo 

```
All required system dependencies are installed.
Installing AFNI.
--2016-10-15 15:25:04--  http://fcp-indi.s3.amazonaws.com/resources/cc_afni_trusty_openmp_64.tar.gz
Resolving fcp-indi.s3.amazonaws.com (fcp-indi.s3.amazonaws.com)... 52.216.16.80
Connecting to fcp-indi.s3.amazonaws.com (fcp-indi.s3.amazonaws.com)|52.216.16.80|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-10-15 15:25:05 ERROR 404: Not Found.
```

**Comment by ccraddock** [comment]
Hello Pradeep,

We had to move our AWS bucket and this has caused the problem. In the
meantime, AFNI has merged my changes, so we can just use the official AFNI
build. I have updated the install file accordingly and am waiting for the
test to complete. I will let you know the stats.

-cc

**Comment by raamana** [comment]
Thanks Cameron, I will follow up with this.

I was able to get the docker built by starting from bids/base_afni on docker hub, and then installing FSL using CPAC installer script. It works for now, but I would like to make it cleaner and more robust.
