### ISSUE TITLE
Change --mem to --mem_mb

### ISSUE THREAD

**Issue by chrisgorgo** [BIDS-Apps/CPAC#9]
It makes sense to keep this flag consistent across the apps and with the manuscript.

**Comment by chrisgorgo** [comment]
Also see: https://groups.google.com/forum/#!topic/bids-apps-dev/cRLqtQbg8fo

**Comment by ccraddock** [comment]
done and addedd mem_gb, which i like more ;)

**Comment by chrisgorgo** [comment]
;)
